language: python
env:
  global:
  - secure: N3QXZkCM8nZxAlMOz7nVHmHVTDcza/NmRejOMbY9tbdhG6foqVX0bGUmlKqbrgDTpea2NshPh3okEYyFfprI/KEySB3qg7MTWjCAb2/PxIq952kb7aOwfxAJYrt5DtOy21I69FscJVFNUE07zW5BQj/Qs0PsmIqDRWobbYQGpMA=
  - secure: Ak0Gs5Qt/UQKTfTJvfq1W/1Il7k7R3XLsxj4Gpd1i2+6NaLT+L9MINyNmEmqovFN/SeagX2vnSfccy9/g8gzXbKbZvJ1YSw07Jelhy+cv1NAr8j0cwVgBnsTbLW3lQfkx0qHyzRauP7WSW7//enThCBel5csSoTts5vbDE/NPug=
python:
- 2.7
- 3.3
install:
- pip install -r requirements.txt
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- firefox &
- sleep 3
script:
- coverage run --source=revuo,portal manage.py test revuo
after_success:
- coveralls
