language: python
python:
  - 2.7
  - 3.3

install:
  - pip install -r requirements.txt
  - pip install -U django==$DJANGO_VERSION

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "firefox &"
  - sleep 3

script:
  - coverage run --source=revuo,portal manage.py test revuo

after_success:
  - coveralls
